### ISSUE TITLE
Game trace implementation

### ISSUE THREAD

**Issue by Konkrad** [riftadi/dragonsarena#14]
use the provided game trace archive to test the system. See http://gta.st.ewi.tudelft.nl/

**Comment by riftadi** [comment]
I've processed one of the trace from [TUD's Game State Archive](http://gta.st.ewi.tudelft.nl/datasets/gta-t3/), cleaned it, and put it in the repo.

It's on the [game_trace.csv](https://github.com/riftadi/dragonsarena/blob/master/game_trace.csv) file.

To do list:
- [x] Retrieve and clean the game trace data
- [x] Implement client resiliency, the client state shoul be saved on the servers, so players can log in and out anytime
- [ ] Create the game trace script executor
