### ISSUE TITLE
Design separation of modeller classes better

### ISSUE THREAD

**Issue by riftadi** [riftadi/dragonsarena#2]
The design now is a mess because it is a quick fix for previous simple design. Create better design for the TSSEngine, GameState, GameBoard, Characters, and Bots classes.

**Comment by Konkrad** [comment]
you already have ideas on how to do it?

**Comment by riftadi** [comment]
yes, it's quite simple actually, i just have to re-organize functions in TSSEngine, GameState, and GameBoard.

**Comment by riftadi** [comment]
somehow, parts of it is done in #18
