### ISSUE TITLE
ZeroMQ

### ISSUE THREAD

**Issue by Konkrad** [riftadi/dragonsarena#6]
Introduce ZeroMQ to make the transfer of the Messages and the Gamestate working over it.

- MSG via ZeroMQ
- Valid Methods to make sure actions of MSG are valid game moves

- Separate Gameboard. Decode it as array of player ids. If a player joins the game the server assigns a position and spreads it.

**Comment by riftadi** [comment]
i think this is done in PR #7, so closing it now.
